name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza diariamente
  workflow_dispatch:      # Permite executar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: Gui-GitHub  # 👈 Nome de usuário **exato** (sem ${{ }} aqui)
          outputs: docs/snake.svg      # Caminho do arquivo de saída

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/snake.svg
          git commit -m "Update snake animation"
          git push
