name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 🔄 Importante para histórico completo

      - name: Create docs directory
        run: mkdir -p docs  # ✅ Garante que a pasta existe

      - name: Generate Snake
        uses: Platane/snk@main
        with:
          github_user_name: Gui-GitHub
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: docs/snake.svg
          color_border: '#1a1a1a'
          color_pipe: '#1a1a1a'
          color_dot: '#3cba54'

      - name: Commit and Push
        if: github.event_name == 'schedule' || github.event.inputs.force == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Força a adição do arquivo mesmo se ignorado no .gitignore
          git add -f docs/snake.svg
          
          # Commit condicional
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update snake animation" && git push)
