name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create docs directory
        run: mkdir -p docs

      - name: Generate Snake
        uses: Platane/snk@main
        with:
          github_user_name: Gui-GitHub
          outputs: docs/snake.svg
          args: "docs/snake.svg --without-comments --color 6699ff --background 0d1117"

      - name: Commit and Push
        if: github.event_name == 'schedule' || github.event.inputs.force == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add docs/snake.svg
          if ! git diff --quiet; then
            git commit -m "Update snake animation"
            git push
          fi
