name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite
  workflow_dispatch:     # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: platane/snk@master
        with:
          github_user_name: Gui-GitHub
          svg_path: assets/github-snake.svg
          snake_color: "rgb:181B2A"       # Cor da cobra (cinza escuro)
          background_color: "rgb:0F1117"  # Cor de fundo (preto azulado)

      - name: Commit and Push
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add assets/github-snake.svg
          git commit -m "Update snake"
          git push
