name: Auto Snake
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: Gui-GitHub
          svg_path: output/github-contribution-grid-snake.svg
          dark_mode: true
          theme: '{"background":"#0d1117","grid":"#161b22","contribution":"#6699ff"}'

      - name: Push
        run: |
          git config user.name github-actions
          git add output/
          git commit -m "Update snakes"
          git push
