name: Generate Snake Animation

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Criar pasta docs
        run: mkdir -p docs

      - name: Gerar Snake
        uses: Platane/snk@master
        with:
          github_user_name: Gui-GitHub
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: docs/snake.svg?palette=github-dark  # 🎯 TEMA ESCURO DIRETO

      - name: Fazer Commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add docs/snake.svg
          
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update snake animation"
            git push
          fi
