name: Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write  # Necessário para a versão mais nova

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: platane/snk@v3
        with:
          github_user_name: Gui-GitHub
          output: .github/snake/
          type: both  # Gera SVG e GIF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply Dark Theme
        run: |
          # Corrige cores do SVG
          sed -i 's/#ffffff/#0F1117/g' .github/snake/snake.svg
          sed -i 's/#bfbfbf/#3B82F6/g' .github/snake/snake.svg
          sed -i 's/#f0f0f0/#181B2A/g' .github/snake/snake.svg

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/snake/
          git commit -m "Update snake animation"
          git push
