name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create docs folder
        run: mkdir -p docs

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: Gui-GitHub
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            docs/snake.svg
            docs/snake-dark.svg?palette=github-dark
          svg_relative_to: docs  # 👈 Fixa o posicionamento

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add docs/snake.svg
          git add docs/snake-dark.svg
          
          if ! git diff --quiet; then
            git commit -m "Update snake animation"
            git push
          fi
