name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite
  workflow_dispatch:     # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: platane/snk@v2
        with:
          github_user_name: Gui-GitHub
          svg_out_path: assets/github-snake.svg
          gif_out_path: assets/github-snake.gif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply Dark Theme
        run: |
          sed -i 's/<rect width="100%" height="100%" fill="#.*"\/>/<rect width="100%" height="100%" fill="#0F1117"\/>/' assets/github-snake.svg
          sed -i 's/<path fill="#.*" d="M.*"\/>/<path fill="#181B2A" d="M0 0h100v100H0z"\/><path fill="#3B82F6" d="M.*"\/>/' assets/github-snake.svg

      - name: Commit and Push
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add assets/github-snake.svg
          git commit -m "Update snake"
          git push
